// Generated by CoffeeScript 1.6.3
var PreviewWebGL,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

PreviewWebGL = (function() {
  function PreviewWebGL(container) {
    this.container = container;
    this.Init = __bind(this.Init, this);
    this.Init();
  }

  PreviewWebGL.prototype.Init = function() {
    var ambientLight, directionalLight,
      _this = this;
    this.camera = new THREE.PerspectiveCamera(35, 1, 1, 10000);
    this.camera.position.z = 900;
    this.scene = new THREE.Scene();
    ambientLight = new THREE.AmbientLight(0x222222);
    this.scene.add(ambientLight);
    directionalLight = new THREE.DirectionalLight(0xffeedd, 1);
    directionalLight.position.set(1, -1, 1).normalize();
    this.scene.add(directionalLight);
    this.sphereMaterial = new THREE.MeshLambertMaterial({
      color: 0xCC0000
    });
    this.sphere = new THREE.Mesh(new THREE.SphereGeometry(150, 32, 32), this.sphereMaterial);
    this.scene.add(this.sphere);
    this.renderer = new THREE.WebGLRenderer({
      antialias: false
    });
    this.renderer.setSize(512, 512);
    this.renderer.setClearColor(0x050505, 1);
    this.renderer.autoClear = false;
    this.container.appendChild(this.renderer.domElement);
    return requestAnimationFrame(function(timestamp) {
      return _this.Render(timestamp);
    });
  };

  PreviewWebGL.prototype.Render = function(timestamp) {
    this.renderer.clear();
    return this.renderer.render(this.scene, this.camera);
  };

  return PreviewWebGL;

})();
